name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest code
        run: |
          cd /var/www/html/laravel
          git pull origin main

      - name: Install dependencies and build
        run: |
          cd /var/www/html/laravel
          cp .env.prod .env
          npm install
          npm run build
